server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: shop
          uri: lb://shop
          predicates:
            - Path=/shop/**
        - id: warehouse
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: email
          uri: lb://email
          predicates:
            - Path=/email/**
